# Generated by Django 4.2.6 on 2023-10-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Minter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageID', models.IntegerField(default=-1)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('IPFS_image', models.CharField(blank=True, max_length=100)),
                ('tokenURI', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visualizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.FileField(upload_to='')),
                ('result', models.ImageField(blank=True, upload_to='')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
